apiVersion: "nuclio.io/v1beta1"
kind: "NuclioFunction"
metadata:
  name: sensorvaluesfunction
spec:
  description: >
    Simply function that gets sensor values, generate log and sends it to topics.
  runtime: "python:3.6"
  handler: "main:handler"
  minReplicas: 1
  maxReplicas: 1
  triggers:
    triggerTopic:
      kind: "rabbit-mq"
      url: "amqp://admin:serverlessistheway@192.168.1.156:5672"
      attributes:
        exchangeName: "topic.sensors"
        queueName: "sensor_values"
  build:
    commands:
      - "pip install pika"
    functionSourceCode: "ZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUKCmltcG9ydCBwaWthCgoKZGVmIHNlbmRfbWVzc2FnZShjaGFubmVsLCBxdWV1ZSwgZGF0YSk6CiAgICBjaGFubmVsLnF1ZXVlX2RlY2xhcmUocXVldWU9cXVldWUpCiAgICBjaGFubmVsLmJhc2ljX3B1Ymxpc2goZXhjaGFuZ2U9JycsCiAgICAgICAgICAgICAgICAgICAgICAgICAgcm91dGluZ19rZXk9cXVldWUsCiAgICAgICAgICAgICAgICAgICAgICAgICAgYm9keT1ieXRlcyhkYXRhLCBlbmNvZGluZz0ndXRmOCcpKQoKCmRlZiBjcmVhdGVfY29ubmVjdGlvbigpOgogICAgY3JlZGVudGlhbHMgPSBwaWthLlBsYWluQ3JlZGVudGlhbHMoImFkbWluIiwgInNlcnZlcmxlc3Npc3RoZXdheSIpCiAgICBjb25uZWN0aW9uID0gcGlrYS5CbG9ja2luZ0Nvbm5lY3Rpb24oCiAgICAgICAgcGlrYS5Db25uZWN0aW9uUGFyYW1ldGVycyhob3N0PScxOTIuMTY4LjEuMTU2JywgcG9ydD01NjcyLCBjcmVkZW50aWFscz1jcmVkZW50aWFscykpCiAgICByZXR1cm4gY29ubmVjdGlvbi5jaGFubmVsKCkKCgpkZWYgZ2V0X2Rhbmdlcih4KToKICAgIHJldHVybiBpbnQoKHggLSAyODApICogKDMgLSAxKSAvICg4MDAgLSAyODApICsgMSkgKyAxCgoKZGVmIGdlbmVyYXRlX21lc3NhZ2UoZGFuZ2VyLCBib2R5KToKICAgIGlmIGRhbmdlciA9PSAxOgogICAgICAgIHNldmVyaXR5ID0gIkxPVyIKICAgIGVsaWYgZGFuZ2VyID09IDI6CiAgICAgICAgc2V2ZXJpdHkgPSAiTUVESVVNIgogICAgZWxpZiBkYW5nZXIgPT0gMzoKICAgICAgICBzZXZlcml0eSA9ICJISUdIIgogICAgZWxzZToKICAgICAgICBzZXZlcml0eSA9ICJFUlJPUiIKCiAgICBub3cgPSBkYXRldGltZS5ub3coKQogICAgZHRfc3RyaW5nID0gbm93LnN0cmZ0aW1lKCIlZC8lbS8lWSAlSDolTTolUyIpCiAgICByZXR1cm4gZiJJTkZPIC0gRGFuZ2VyOiB7c2V2ZXJpdHl9IC0gU2Vuc29yIHZhbHVlOiB7Ym9keX0gLSBEYXRlOiB7ZHRfc3RyaW5nfSIKCgpkZWYgaGFuZGxlcihjb250ZXh0LCBldmVudCk6CiAgICBib2R5ID0gaW50KGV2ZW50LmJvZHkuZGVjb2RlKCkpCiAgICBjb250ZXh0LmxvZ2dlci5pbmZvKGYnUmVjZWl2ZWQgYm9keToge2JvZHl9JykKICAgIGRhbmdlciA9IGdldF9kYW5nZXIoYm9keSkKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oZidEYW5nZXIgYm9keToge2Rhbmdlcn0nKQogICAgbWVzc2FnZSA9IGdlbmVyYXRlX21lc3NhZ2UoZGFuZ2VyLCBib2R5KQogICAgY29udGV4dC5sb2dnZXIuaW5mbyhmJ0dlbmVyYXRlZCBtZXNzYWdlOiB7bWVzc2FnZX0nKQogICAgY2hhbm5lbCA9IGNyZWF0ZV9jb25uZWN0aW9uKCkKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oJ1NlbmRpbmcgbWVzc2FnZSBmb3IgbG9nIHF1ZXVlJykKICAgIHNlbmRfbWVzc2FnZShjaGFubmVsLCAibG9nIiwgbWVzc2FnZSkKICAgIGlmIGRhbmdlciA9PSAzOgogICAgICAgIGNvbnRleHQubG9nZ2VyLmluZm8oJ1NlbmRpbmcgbWVzc2FnZSBmb3IgYWxhcm0gcXVldWUnKQogICAgICAgIHNlbmRfbWVzc2FnZShjaGFubmVsLCAiYWxhcm0iLCBtZXNzYWdlKQogICAgcmV0dXJuCg=="

