apiVersion: "nuclio.io/v1beta1"
kind: "NuclioFunction"
metadata:
  name: sensorvaluesfunction
spec:
  description: >
    Simply function that gets sensor values, generate log and sends it to topics.
  runtime: "python:3.6"
  handler: "main:handler"
  minReplicas: 1
  maxReplicas: 1
  triggers:
    myNatsTopic:
      kind: "rabbit-mq"
      url: "amqp://admin:serverlessistheway@192.168.56.1:5672"
      attributes:
        exchangeName: "topic.sensors"
        queueName: "sensor_values"
  build:
    commands:
      - "pip install pika"
    functionSourceCode: "ZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUKCmltcG9ydCBwaWthCgoKZGVmIHNlbmRfbWVzc2FnZShjaGFubmVsLCBxdWV1ZSwgZGF0YSk6CiAgICBjaGFubmVsLnF1ZXVlX2RlY2xhcmUocXVldWU9cXVldWUpCiAgICBjaGFubmVsLmJhc2ljX3B1Ymxpc2goZXhjaGFuZ2U9JycsCiAgICAgICAgICAgICAgICAgICAgICAgICAgcm91dGluZ19rZXk9cXVldWUsCiAgICAgICAgICAgICAgICAgICAgICAgICAgYm9keT1ieXRlcyhkYXRhLCBlbmNvZGluZz0ndXRmOCcpKQoKCmRlZiBjcmVhdGVfY29ubmVjdGlvbigpOgogICAgY3JlZGVudGlhbHMgPSBwaWthLlBsYWluQ3JlZGVudGlhbHMoImFkbWluIiwgInNlcnZlcmxlc3Npc3RoZXdheSIpCiAgICBjb25uZWN0aW9uID0gcGlrYS5CbG9ja2luZ0Nvbm5lY3Rpb24oCiAgICAgICAgcGlrYS5Db25uZWN0aW9uUGFyYW1ldGVycyhob3N0PScxOTIuMTY4LjU2LjEnLCBwb3J0PTU2NzIsIGNyZWRlbnRpYWxzPWNyZWRlbnRpYWxzKSkKICAgIHJldHVybiBjb25uZWN0aW9uLmNoYW5uZWwoKQoKCmRlZiBnZXRfZGFuZ2VyKHgpOgogICAgcmV0dXJuIGludCgoeCAtIDI4MCkgKiAoMyAtIDEpIC8gKDgwMCAtIDI4MCkgKyAxKSArIDEKCgpkZWYgZ2VuZXJhdGVfbWVzc2FnZShkYW5nZXIsIGJvZHkpOgogICAgaWYgZGFuZ2VyID09IDE6CiAgICAgICAgc2V2ZXJpdHkgPSAiTE9XIgogICAgZWxpZiBkYW5nZXIgPT0gMjoKICAgICAgICBzZXZlcml0eSA9ICJNRURJVU0iCiAgICBlbGlmIGRhbmdlciA9PSAzOgogICAgICAgIHNldmVyaXR5ID0gIkhJR0giCiAgICBlbHNlOgogICAgICAgIHNldmVyaXR5ID0gIkVSUk9SIgoKICAgIG5vdyA9IGRhdGV0aW1lLm5vdygpCiAgICBkdF9zdHJpbmcgPSBub3cuc3RyZnRpbWUoIiVkLyVtLyVZICVIOiVNOiVTIikKICAgIHJldHVybiBmIklORk8gLSBEYW5nZXI6IHtzZXZlcml0eX0gLSBTZW5zb3IgdmFsdWU6IHtib2R5fSAtIERhdGU6IHtkdF9zdHJpbmd9IgoKCmRlZiBoYW5kbGVyKGNvbnRleHQsIGV2ZW50KToKICAgIGJvZHkgPSBpbnQoZXZlbnQuYm9keS5kZWNvZGUoKSkKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oZidSZWNlaXZlZCBib2R5OiB7Ym9keX0nKQogICAgZGFuZ2VyID0gZ2V0X2Rhbmdlcihib2R5KQogICAgY29udGV4dC5sb2dnZXIuaW5mbyhmJ0RhbmdlciBib2R5OiB7ZGFuZ2VyfScpCiAgICBtZXNzYWdlID0gZ2VuZXJhdGVfbWVzc2FnZShkYW5nZXIsIGJvZHkpCiAgICBjb250ZXh0LmxvZ2dlci5pbmZvKGYnR2VuZXJhdGVkIG1lc3NhZ2U6IHttZXNzYWdlfScpCiAgICBjaGFubmVsID0gY3JlYXRlX2Nvbm5lY3Rpb24oKQogICAgY29udGV4dC5sb2dnZXIuaW5mbygnU2VuZGluZyBtZXNzYWdlIGZvciBsb2cgcXVldWUnKQogICAgc2VuZF9tZXNzYWdlKGNoYW5uZWwsICJsb2ciLCBtZXNzYWdlKQogICAgaWYgZGFuZ2VyID09IDM6CiAgICAgICAgY29udGV4dC5sb2dnZXIuaW5mbygnU2VuZGluZyBtZXNzYWdlIGZvciBhbGFybSBxdWV1ZScpCiAgICAgICAgc2VuZF9tZXNzYWdlKGNoYW5uZWwsICJhbGFybSIsIG1lc3NhZ2UpCiAgICByZXR1cm4K"

